---
- name: Define Paramenters
  hosts: iosxe_devices
  connection: network_cli
  tasks:
    - name: load new acl into device
      ios_config:
        lines:
          - 10 permit ip host 10.10.20.49 any log
          - 20 permit ip host 10.10.20.50 any log
          - 30 permit ip host 10.10.20.51 any log
        parents: ip access-list extended my_acl
        before: no ip access-list extended my_acl
        match: exact